# Generated by Django 6.0 on 2025-12-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "admin"),
                    ("MENTOR", "mentor"),
                    ("STUDENT", "student"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
